MERGE INTO ratings (rating_id, rating_name) VALUES (1, 'G');
MERGE INTO ratings (rating_id, rating_name) VALUES (2, 'PG');
MERGE INTO ratings (rating_id, rating_name) VALUES (3, 'PG-13');
MERGE INTO ratings (rating_id, rating_name) VALUES (4, 'R');
MERGE INTO ratings (rating_id, rating_name) VALUES (5, 'NC-17');

MERGE INTO genres (genre_id, genre_name) VALUES (1, 'Боевик');
MERGE INTO genres (genre_id, genre_name) VALUES (2, 'Приключения');
MERGE INTO genres (genre_id, genre_name) VALUES (3, 'Комедия');
MERGE INTO genres (genre_id, genre_name) VALUES (4, 'Драма');
MERGE INTO genres (genre_id, genre_name) VALUES (5, 'Фэнтези');
MERGE INTO genres (genre_id, genre_name) VALUES (6, 'Ужасы');
MERGE INTO genres (genre_id, genre_name) VALUES (7, 'Мистика');
MERGE INTO genres (genre_id, genre_name) VALUES (8, 'Romance');
MERGE INTO genres (genre_id, genre_name) VALUES (9, 'Научная фантастика');
MERGE INTO genres (genre_id, genre_name) VALUES (10, 'Триллер');
MERGE INTO genres (genre_id, genre_name) VALUES (11, 'Мультфильм');
MERGE INTO genres (genre_id, genre_name) VALUES (12, 'Документальный');
MERGE INTO genres (genre_id, genre_name) VALUES (13, 'Мюзикл');
MERGE INTO genres (genre_id, genre_name) VALUES (14, 'Вестерн');
MERGE INTO genres (genre_id, genre_name) VALUES (15, 'Исторический');
MERGE INTO genres (genre_id, genre_name) VALUES (16, 'Спорт');
MERGE INTO genres (genre_id, genre_name) VALUES (17, 'Супергеройский');
MERGE INTO genres (genre_id, genre_name) VALUES (18, 'Семейный');
MERGE INTO genres (genre_id, genre_name) VALUES (19, 'Военный');
MERGE INTO genres (genre_id, genre_name) VALUES (20, 'Криминал');