CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ratings (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    film_id LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    release_date DATE NOT NULL,
    duration LONG NOT NULL,
    mpa_rating_id INTEGER NOT NULL,
    CONSTRAINT fk_mpa_rating_id FOREIGN KEY (mpa_rating_id) REFERENCES ratings (rating_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship_statuses (
    user_id LONG NOT NULL,
    friend_id LONG NOT NULL,
    status BOOLEAN NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_friend_id FOREIGN KEY (friend_id) REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id LONG NOT NULL,
    liked_user_id LONG NOT NULL,
    CONSTRAINT fk_film_id1 FOREIGN KEY (film_id) REFERENCES films (film_id),
    CONSTRAINT fk_liked_user_id FOREIGN KEY (liked_user_id) REFERENCES users (user_id),
    PRIMARY KEY (film_id, liked_user_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id LONG NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT fk_film_id2 FOREIGN KEY (film_id) REFERENCES films (film_id),
    CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
);